### ISSUE TITLE
Declaration or statement expected error in index.d.ts

### ISSUE THREAD

**Issue by adred** [STORIS/react-scrollbar-size#115]
Wrong export of `ScrollbarSizeChangeHandlerParams` and `ScrollbarSizeProps` that causes `Declaration or statement expected` error.

It should look like this:
```
import ScrollbarSize, { ScrollbarSizeChangeHandlerParams, ScrollbarSizeProps } from './ScrollbarSize';
export { ScrollbarSizeChangeHandlerParams, ScrollbarSizeProps };
export default ScrollbarSize;
```

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/STORIS/react-scrollbar-size/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

My project fails to load.

## Expected Behavior 🤔

It should load.

## Steps to Reproduce 🕹

Steps:

1. Install
2. Import and use `ScrollbarSize` and `ScrollbarSizeChangeHandlerParams`
3. Run project

## Context 🔦

I'm simply trying to use it.

## Your Environment 🌎

| Tech                 | Version |
| -------------------- | ------- |
| React-Scrollbar-Size | v3.0.1  |
| React                |    16.13.1     |
| Browser              |   Chrome      |
| TypeScript           |   3.7.2      |

I forked the repo and created a fix. If you want me to create PR I'll gladly do so. Just let me know which branch to merge.

**Comment by shawnmcknight** [comment]
The concern I have with your solution is that the `index.js` file ends up with properties for the `ScrollbarSizeChangeHandlerParams` and `ScrollbarSizeProps` as a result.  Since those properties are simply types, they do not belong in the emitted JavaScript.  This is where the `export type` annotation comes into play as it causes the transpiler to skip emitting those properties.

However, TS did not begin to support "type-only" imports and exports until [version 3.8](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html),  From your environment, it seems that you are presently using TS 3.7.2.  Is upgrading your TS version an option?

**Comment by adred** [comment]
@shawnmcknight Upgrading to the latest TS solved the problem. Thanks!
