### ISSUE TITLE
Error from lodash peerDependency

### ISSUE THREAD

**Issue by twobitfool** [STORIS/react-scrollbar-size#7]
When adding material-ui (v1 beta) to a project, I get an error...

`react-scrollbar-size@2.0.2 requires a peer of lodash@^4.17.0 but none was installed.` 

My project is still using lodash v3, and upgrading lodash would be a pretty crazy effort. 

Would it be possible to reduce the lodash version required by react-scrollbar-size? I think that `throttle` worked the same in lodash v3. 

Or, alternately, how about using a regular dependency (instead of peerDependency) for the one function needed: **lodash.throttle**? 

Thanks :)

**Comment by shawnmcknight** [comment]
Some background on the use of lodash as a peerDep:
In #3, it was requested that I make lodash a peerDep by the maintainer of material-ui.  As material-ui is the major consumer of this repo, I didn't see a problem with doing that.

Now, with that said, your issue doesn't really make a whole lot of sense, but I can duplicate it.  You should not have to install a compatible version of lodash in your repo, as you are not the consumer of `react-scrollbar-size`.  As the consumer of `react-scrollbar-size`, `material-ui` should have to install lodash as part of its dependencies.  In reviewing https://github.com/mui-org/material-ui/blob/v1-beta/package.json they are set to have lodash `^4.2.0`.  In theory, on a clean install, a semver of ^4.2.0 should result in an actually installed version of `4.17.4` since that's the latest version that matches the compatibility spec.

In testing, if I initialize a new project and `npm install react react-dom material-ui@next` I end up with the following tree for lodash:
```
λ npm ls lodash
test@1.0.0 C:\Users\Shawn\Projects\test
`-- material-ui@1.0.0-beta.31
  `-- lodash@4.17.4
```

That looks like exactly what I would have expected.  `lodash@4.17.4` was installed subordinate to `material-ui`.

However, if I mix things up and instead do an install of `lodash@3.10.0` BEFORE the other install:
```
λ npm install lodash@3.10.0
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN test2@1.0.0 No description
npm WARN test2@1.0.0 No repository field.

+ lodash@3.10.0
added 1 package in 0.712s

λ npm install react react-dom material-ui@next

> jss@9.6.0 postinstall C:\Users\Shawn\Projects\test2\node_modules\jss
> node -e "console.log('\u001b[35m\u001b[1mLove JSS? You can now support us on open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/jss/donate\u001b[0m')"

Love JSS? You can now support us on open collective:
 > https://opencollective.com/jss/donate
npm WARN react-scrollbar-size@2.0.2 requires a peer of lodash@^4.17.0 but none is installed. You must install peer dependencies yourself.
npm WARN test2@1.0.0 No description
npm WARN test2@1.0.0 No repository field.

+ material-ui@1.0.0-beta.31
+ react-dom@16.2.0
+ react@16.2.0
added 68 packages in 4.219s

λ npm ls lodash
test2@1.0.0 C:\Users\Shawn\Projects\test2
`-- lodash@3.10.0
```

In this case, npm does not indicate that lodash@4.17.4 was installed.  If that were actually the case, then the project isn't even meeting the requirements of material-ui since 3.10.0 is not compatible with ^4.2.0.

However, in ACTUALLY looking at what was installed, I can see that in `node_modules/material-ui/node_modules/lodash` there is, in fact, version 4.17.4 of lodash installed.  That is exactly what I would have expected, although `npm ls` isn't indicating it.

In my functioning repo, an `npm ls` output shows:
```
+-- material-ui@1.0.0-beta.31
...
| +-- lodash@4.17.4
...
| +-- react-scrollbar-size@2.0.2
...
```
but in the bad repo:
```
+-- lodash@3.10.0
+-- material-ui@1.0.0-beta.31
...
| +-- UNMET PEER DEPENDENCY lodash@4.17.4
...
| +-- react-scrollbar-size@2.0.2
...
```

While I don't necessarily have an issue with changing my dependency for lodash, I'm not convinced this is a problem with this repo.  It appears to me that npm is doing some strange things with the installation of the modules and its resulting in this undesirable behavior.  I'm going to give a try with an older version of npm (pre v5) just to see if it behaves any differently.

**Comment by shawnmcknight** [comment]
Well, in terms of good news, this doesn't appear to be a regression in npm.  I tested on 3.x.x and 4.x.x and the same behavior happened.  Perhaps I've got a misunderstanding of exactly how peerDeps are supposed to work, but either way, it looks like a problem.

Let me think on it and decide how I'd like to approach it.  The most logical thing is probably to go with the direct dependency of lodash.throttle, but I'd like to give it a bit of thought before I leap to that conclusion.

**Comment by twobitfool** [comment]
@shawnmcknight -- A huge thanks for such a thorough and thoughtful reply! 👍 

Another option, if you'd like... I could whip up a throttle function, without all the extra (unused) bells and whistles that come with `lodash.throttle`.

**Comment by twobitfool** [comment]
@shawnmcknight -- In case you decide you want it, I threw together a little throttle function. It's wrapped up in a little package called [stifle](https://github.com/twobitfool/stifle).

I pulled in all of the relevant `throttle` tests from lodash, and because it doesn't include any of the "bells and whistles" that you don't need, it's over an order of magnitude faster -- in my totally contrived, and meaningless benchmarks ;)

If you'd rather not have another dependency, feel free to just drop this code (from `stifle`) right in to your project...

```javascript

function throttle (fn, wait) {
  var timer;    
  var called;   
  
  var wrapper = function () {
    if (timer) {
      called = true;
    } else {
      timer = setTimeout(afterWait, wait);
      fn();
    }
  }

  wrapper.cancel = function () {
    if (timer) clearTimeout(timer)
    timer = undefined
  }

  function afterWait() {
    timer = undefined;
    if (called) {
      called = false;
      wrapper()
    }
  }

  return wrapper;
}
```

Hope that helps, and thanks again :)

**Comment by shawnmcknight** [comment]
That actually does help quite a bit.  I like the simplicity of the package and I'll avoid the weight of carrying around the extra fluff that's in lodash.  I went ahead and published a new version that eliminates the `lodash` peerDep and makes `stifle` a dependency.  A fresh install of `material-ui` should grab the latest version of `react-scrollbar-size` and you should hopefully be good to go. Enjoy!

**Comment by twobitfool** [comment]
Awesome. Thanks!
